INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('57', '50 Packers Park', 'Kaduranca', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('18', '63802 Monterey Way', 'Guchang', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('97', '7 Moland Plaza', 'Maintang', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('24', '71 Acker Road', 'Penelas', 'Portugal');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('38', '9082 Mallard Avenue', 'Lianokládhion', 'Greece');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('9', '6 Kinsman Center', 'Kujang', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('74', '1109 Truax Park', 'Grivenskaya', 'Russia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('28', '676 Stuart Terrace', 'Bantian', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('82', '5 Kinsman Crossing', 'São João da Barra', 'Brazil');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('38', '29198 Butterfield Court', "Priob\'ye", 'Russia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('80', '12152 Arkansas Park', 'Guozhai', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('63', '21041 Golden Leaf Terrace', 'Gumel', 'Nigeria');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('91', '62 Kings Terrace', 'Arenal', 'Peru');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('4', '6647 Nobel Trail', 'Issoire', 'France');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('98', '121 Hermina Circle', 'Guanli', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('91', '5808 Acker Plaza', 'Hrastnik', 'Slovenia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('12', '427 Maryland Point', 'Manicaragua', 'Cuba');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('45', '23111 Rusk Lane', 'Pasaco', 'Guatemala');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('34', '56866 Donald Street', 'São Silvestre', 'Portugal');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('43', '8902 Pierstorff Pass', 'Masākin', 'Tunisia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('13', '82 Manley Pass', 'Kaum', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('3', '0 Scofield Alley', 'Quellouno', 'Peru');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('11', '854 Comanche Road', 'Rennes', 'France');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('95', '5 Artisan Way', 'San Lucas', 'Philippines');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('27', '41092 Mesta Alley', 'Xinglin', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('43', '42 Waubesa Hill', 'Godong', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('83', '9514 Northport Trail', 'Pyay', 'Myanmar');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('80', '831 Waywood Trail', 'Bilyarsk', 'Russia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('33', '7193 Dunning Alley', 'Kuidou', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('3', '1 Atwood Parkway', 'Filipstad', 'Sweden');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('97', '09392 Sommers Pass', 'Kvissleby', 'Sweden');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('12', '2583 Lotheville Way', 'Washington', 'United States');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('9', '0285 Basil Lane', 'Chojnów', 'Poland');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('70', '92798 Ruskin Place', 'Zarechnyy', 'Russia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('70', '59 Bluestem Park', 'Baiyangwan', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('83', '671 John Wall Hill', 'Bezerros', 'Brazil');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('15', '23 Riverside Road', 'Xigaoshan', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('98', '36842 Blaine Alley', 'Isfana', 'Kyrgyzstan');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('83', '5 Del Sol Lane', 'Dębnica Kaszubska', 'Poland');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('33', '5434 Vernon Way', 'Aricagua', 'Venezuela');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('42', '114 Kim Street', 'Bato', 'Philippines');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('20', '756 Larry Crossing', 'Luebo', 'Democratic Republic of the Congo');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('68', '8008 Spenser Lane', 'Novyy Urgal', 'Russia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('36', '55 Forest Run Junction', 'Uchaly', 'Russia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('7', '36733 Goodland Center', 'Huifa', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('63', '114 Merrick Trail', 'Delray Beach', 'United States');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('43', '7 Troy Street', 'Měřín', 'Czech Republic');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('14', '47 Montana Alley', 'Nansha', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('32', '78879 Hauk Point', 'Kotel', 'Bulgaria');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('59', '32 Morning Court', 'Volgo-Kaspiyskiy', 'Russia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('27', '6771 Express Park', 'Zürich', 'Switzerland');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('17', '67 Hansons Trail', 'Tunguang', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('20', '0474 Sullivan Point', 'Lacabamba', 'Peru');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('7', '30 Moland Road', 'La Agustina', 'Dominican Republic');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('16', '44706 Hallows Street', 'Muroran', 'Japan');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('5', '4712 Bashford Plaza', 'Lazaro Cardenas', 'Mexico');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('33', '165 Mayer Trail', 'Letuyi', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('6', '9 Utah Point', 'Fifi', 'Morocco');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('58', '8857 Logan Terrace', 'Ouango', 'Central African Republic');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('50', '167 Kenwood Lane', 'Oebaki', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('66', '81 Sullivan Point', 'Wuxihe', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('34', '5724 Macpherson Road', 'Licheń Stary', 'Poland');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('91', '4 Veith Pass', 'Quinta dos Frades', 'Portugal');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('50', '642 Summerview Road', 'Kiryandongo', 'Uganda');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('50', '9834 Forster Parkway', 'Fálanna', 'Greece');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('49', '8 Orin Terrace', 'Jeberos', 'Peru');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('80', '23025 Ridgeview Pass', 'Itaparica', 'Brazil');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('43', '48 Roxbury Circle', 'Hougong', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('59', '614 Forest Dale Trail', 'Lelystad', 'Netherlands');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('90', '05 Oxford Place', 'Kolwezi', 'Democratic Republic of the Congo');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('36', '035 Fuller Circle', 'Kamalaputi', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('70', '0468 Artisan Junction', 'Balad', 'Iraq');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('6', '08 Waubesa Way', 'Zbąszynek', 'Poland');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('2', '52019 Westridge Point', 'Kurunegala', 'Sri Lanka');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('13', '25 Boyd Street', 'Brive-la-Gaillarde', 'France');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('71', '6 Schmedeman Place', 'Trondheim', 'Norway');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('9', '21 Blue Bill Park Terrace', 'Morazán', 'Honduras');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('5', '8352 La Follette Trail', 'Otterburn Park', 'Canada');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('21', '583 Green Ridge Court', 'Villeneuve-sur-Lot', 'France');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('28', '814 Dryden Drive', 'Banjar Triwangsakeliki', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('96', '47 Tennessee Drive', 'Charlotte', 'United States');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('38', '2 Morning Pass', 'Hamburg', 'Germany');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('46', '96836 Iowa Center', 'Songnim', 'North Korea');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('73', '1 Forest Dale Center', 'Longkou', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('55', '8 Warbler Junction', 'Lapaz', 'Philippines');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('76', '6690 Clarendon Alley', 'Pakel', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('12', '64614 Sommers Crossing', 'Belo sur Tsiribihina', 'Madagascar');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('97', '08 Acker Road', 'Naikoten Dua', 'Indonesia');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('61', '30461 Fuller Parkway', 'Hengelo', 'Netherlands');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('62', '149 Cherokee Court', 'Lidköping', 'Sweden');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('7', '466 Independence Circle', 'Shiroi', 'Japan');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('64', '4 Welch Crossing', 'La Jutosa', 'Honduras');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('85', '7030 Packers Trail', 'Burgersfort', 'South Africa');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('75', '292 Kipling Crossing', 'Zhangdian', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('86', '05156 Stoughton Park', 'Zarrīn Shahr', 'Iran');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('47', '9178 Oneill Terrace', 'Gaoling', 'China');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('55', '45 Victoria Trail', 'Bálsamo Oriental', 'Honduras');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('50', '0 Express Street', 'Ishii', 'Japan');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('57', '4253 Coolidge Center', 'Zunilito', 'Guatemala');
INSERT INTO shipping_details (order_ID, address, city, country) VALUES ('85', '69196 Longview Place', 'Sekartaji', 'Indonesia');
